config/routes.rb
Listofgifs::Application.routes.draw do
  root to: 'gifs#index'

  resource :status, only: :show
  resources :gifs do
    collection do
      get :import
      get :random
      get :nsfw
    end
  end

  resources :unpublished_gifs do
    member do
      get :share
    end
    collection do
      get :nsfw
      delete :empty_trash
      delete :delete_all
    end
  end

  resources :gif_search_results, only: :index

  get '/sitemap', to: 'sitemap#index', defaults: { format: 'xml' }

  get '/channel.html' => proc {
    [
      200,
      {
        'Pragma'        => 'public',
        'Cache-Control' => "max-age=#{1.year.to_i}",
        'Expires'       => 1.year.from_now.to_s(:rfc822),
        'Content-Type'  => 'text/html'
      },
      ['<script src="//connect.facebook.net/en_US/all.js"></script>']
    ]
  }
  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'
end

app/models/gif.rb
class Gif < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :url
  paginates_per 4

  scope :unpublished, ->{ where(published_at: nil) }
  scope :published, ->{ where("published_at is NOT ?", nil).where('hidden is ? or hidden = ?', nil, false) }
  scope :sfw, ->{ where('nsfw is ? or nsfw = ?', nil, false) }
  scope :nsfw, ->{ where(nsfw: true) }
  scope :visible, ->{ published.sfw }
  scope :random, ->{ order('random()') }
  scope :ordered, ->{ order('published_at DESC').order('created_at DESC').order('id DESC') }
  scope :in_trash, ->{ where(hidden: true) }
  scope :not_shared, ->{ where.not(shared: true) }

  attr_accessor :social_share

  def self.search(query)
    Gif.visible.fuzzy_search(title: query)
  end

  def prev
    Gif.visible.order(:id).where("id > ?", id).first || Gif.visible.order(:id).first
  end

  def next
    Gif.visible.order(:id).where("id < ?", id).last || Gif.visible.order(:id).last
  end

  def to_param
    return super unless persisted?
    "#{id}-#{title.to_s.downcase.gsub(/[^a-zA-Z0-9]+/, '-').gsub(/-{2,}/, '-').gsub(/^-|-$/, '')}"
  end

  def self.pick_random
    visible.random.first
  end

  def self.by_params(params)
    Gif.visible.ordered.page(params[:page])
  end

  def publish
    self.published_at = Time.now.utc
  end

  def publish!
    publish
    save!
  end

  def videoable?
    url.to_s.match(/imgur\.com\/\w+\.gif$/)
  end

  def url_for_format(format, query_params = '')
    raise "Gif not videoable" unless videoable?
    url.gsub('.gif', format) + query_params
  end

  def directified_url
    if url.to_s.match(/imgur\.com\/(gallery\/)?\w+$/)
      url.gsub(/gallery\//, '').gsub(/imgur/, 'i.imgur') + '.gif'
    else
      url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gif_search_results_controller.rb
require 'reddit'
class GifSearchResultsController < ApplicationController
  respond_to :html, :js, :json, :xml

  def index
  end

private
  def gifs
    @gifs ||= Gif.search(params[:q]).limit(100)
  end
  helper_method :gifs

  def admin_helpers?
    false
  end
  helper_method :admin_helpers?
end

app/controllers/gifs_controller.rb
require 'reddit'
class GifsController < ApplicationController
  include GifsHelper
  http_basic_authenticate_with name: "admin", password: ENV['GIFLIST_ADMIN_PASSWORD'], only: [:nsfw]
  respond_to :html, :js, :json, :xml

  def index
    respond_with gifs
  end

  def show
    @title = gif.title
    @prev_gif = gif.prev
    @next_gif = gif.next
  end

  def random
    redirect_to action: :show, id: Gif.pick_random
  end

  def nsfw
    @gifs = Gif.nsfw.published.ordered.page(params[:page]).per(20)
    render template: 'gifs/index'
  end

  def import
    Reddit.new.delay.import
    if params[:admin]
      redirect_to unpublished_gifs_url
    else
      redirect_to root_url
    end
  end

private
  def admin_helpers?
    cookies.signed[:admin_helpers] == true
  end
  helper_method :admin_helpers?
end

app/controllers/gifs_helper.rb
module GifsHelper

  def self.included(c)
    if defined?(c.helper_method)
      c.helper_method :gif, :gifs
    end
  end

private
  def gif
    @gif ||= Gif.find params[:id]
  end

  def gifs
    @gifs ||= Gif.by_params params
  end
end

app/controllers/sitemap_controller.rb
class SitemapController < ApplicationController
  layout nil
  respond_to :xml

  def index
    scoped = Gif.visible.ordered
    last_gif = scoped.last
    if stale?(etag: last_gif, last_modified: last_gif.updated_at.utc)
      respond_to do |format|
        format.xml { @gifs = scoped }
      end
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  respond_to :json
  def show
    today = 1.day.ago..Time.zone.now
    status = {
      healthy: true,
      gif_count: Gif.count,
      new_imported_today: Gif.where(created_at: today).count,
      new_published_today: Gif.visible.where(created_at: today).count,
      new_shared_today: Gif.visible.where(shared: true, created_at: today).count,
      visile: Gif.visible.count,
      failed_jobs: Delayed::Job.where('attempts > 1').count
    }
    respond_with status
  end
end

app/controllers/unpublished_gifs_controller.rb
require 'reddit'
class UnpublishedGifsController < ApplicationController
  include GifsHelper
  http_basic_authenticate_with name: "admin", password: ENV['GIFLIST_ADMIN_PASSWORD']
  respond_to :html, :js, :json, :xml
  after_action :enable_admin_helpers, only: [:index]

  def index
    @gifs = Gif.unpublished.ordered.page(params[:page]).per(20)
  end

  def edit
  end

  def update
    if gif.update_attributes(gif_params)
      social_share(gif)
      respond_to do |wants|
        wants.html { redirect_to gif }
        wants.js { head :ok }
      end
    elsif gif_params[:hidden].to_i > 1 # hiding failed due to a duplicate
      gif.destroy
      respond_to do |wants|
        wants.html { redirect_to unpublished_gifs_path }
        wants.js { head :ok }
      end
    end
  end

  def nsfw
    @gifs = Gif.nsfw.unpublished.ordered.page(params[:page]).per(20)
    render template: 'unpublished_gifs/index'
  end

  def new
    @gif = Gif.new
  end

  def create
    gif = Gif.new gif_params
    if gif.save
      social_share(gif)
      redirect_to gif_path(gif)
    else
      render text: gif.errors.full_messages.join
    end
  end

  def destroy
    if gif.destroy
      redirect_to root_url
    else
      head 500
    end
  end

  def empty_trash
    Gif.in_trash.delete_all
    redirect_to :back
  end

  def delete_all
    Gif.unpublished.delete_all
    redirect_to :back
  end

  def share
    Social.share(gif)
    respond_to do |format|
      format.html { redirect_to :back }
      format.js   { head :ok }
    end
  end

private
  def social_share(gif)
    if gif.social_share.to_i > 0
      Social.share(gif)
    end
  end

  def gif_params
    params.require(:gif).permit(:title, :url, :nsfw, :published_at, :hidden, :social_share)
  end

  def enable_admin_helpers
    cookies.signed[:admin_helpers] = true
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    @title ||= 'The GIF Giraffe'
  end
end

app/views/gif_search_results/index.html.haml
#gif_search
  .user_message
    = "#{pluralize(gifs.to_a.size, 'search result')} for '#{params[:q]}'"

= render gifs

app/views/gifs/_admin_convenience_actions.html.haml
- if admin_helpers?
  %p
    Admin actions:
    = link_to "Edit", edit_unpublished_gif_path(gif)
    \|
    = link_to "Social Share", share_unpublished_gif_path(gif)
    \|
    = link_to "Delete", unpublished_gif_path(gif), method: :delete, data: { confirm: "Are you sure?" }, class: "destructive_action"

app/views/gifs/_embed.html.haml
- if gif.videoable?
  %video{preload: "auto", autoplay: "autoplay", muted: "muted", loop: "loop" }
    %source{src: gif.url_for_format('.mp4'), type: "video/mp4"}
    %source{src: gif.url_for_format('.webm'), type: "video/webm"}
- else
  = link_to gif_path(gif) do
    = image_tag gif.url, alt: gif.title

app/views/gifs/_form.html.haml
.page
  - if gif.persisted?
    %h3= gif.title
    %br
    = image_tag gif.directified_url, class: 'preview'
    %p= gif.url
  %br
  = form_for gif, remote: remote do |f|
    = f.text_field :title, placeholder: 'title'
    %br
    = f.text_field :url, placeholder: 'url', value: gif.directified_url
    %br
    = f.datetime_select :published_at
    = f.label :published_at
    %br
    = label_tag do
      = f.check_box :nsfw
      Adult, porn, NSFW...
    %br
    = label_tag do
      = f.check_box :hidden
      Delete
    %br
    %br
    = f.submit "Save"

app/views/gifs/_gif.html.haml
.page.clearfix[gif]
  = render 'gifs/gif_body', gif: gif

app/views/gifs/_gif_body.html.haml
%article.gif_body
  = link_to gif_path(gif), class: 'heading' do
    %h2= gif.title.to_s.capitalize
  = render 'embed', gif: gif
.gif_secondary
  .social
    = render 'social/share', gif: gif
  = render 'gifs/admin_convenience_actions', gif: gif

app/views/gifs/_social_stripe.html.haml
.social_stripe
  Follow Giffare on
  = link_to "Facebook", "https://facebook.com/giffare"
  and
  = link_to "Twitter", "https://twitter.com/gifgiraffe"
  to see the best gifs in your social feeds.

app/views/gifs/bulk_edit.html.haml
#bulk_edit
  - gifs.each do |gif|
    .editable_gif
      .hidden.done
        Išsaugota
        = link_to "Peržiūrėti", gif_path(gif), target: "_blank"
        = link_to image_tag('tweet.png'), "https://twitter.com/share?text=#{gif.title.gsub(/ /, '+')}&url=#{CGI.escape gif_url(gif)}", class: 'tweet_button', target: :blank
      = render "form", gif: gif, remote: true
      -# = button_to 'Delete', gif, method: :delete, remote: true, confirm: 'U sure?'
  .editable_gif
    = link_to "Next batch", unpublished_gifs_path
    |
    = link_to "Import more", import_gifs_path(admin: true)

app/views/gifs/index.html.haml
#gifs
  = render gifs
= paginate gifs

app/views/gifs/index.js.erb
<%- if gifs.size > 0 %>
  $("#gifs").append("<%= escape_javascript(render(gifs)) %>");
  <%- if rand < 0.3 %>
    $("#gifs").append("<%= escape_javascript(render('social_stripe')) %>");
  <%- end %>
<%- else %>
  $("#no_moar").show()
<%- end %>

app/views/gifs/show.html.haml
= render "shared/ad"
.page.clearfix[gif]
  %article.gif_body
    %h2= gif.title.to_s.capitalize
    = render 'embed', gif: gif
  .gif_secondary
    .social
      = render 'social/share', gif: gif
      = render 'gifs/admin_convenience_actions', gif: gif
    %nav.show
      = link_to gif_path(@prev_gif), rel: 'prev', class: 'prev big_button', title: 'Previous' do
        = "«"
        %span.label Prev
      = link_to random_gifs_path, class: 'random big_button', title: 'Random' do
        = "↻"
        %span.label Random
      = link_to gif_path(@next_gif), rel: 'next', class: 'next big_button', title: 'Next' do
        %span.label Next
        = "»"

.comments.clearfix
  .fb-comments{"data-href" => url_for(:only_path => false), "data-num-posts" => "20", "data-width" => "600"}

app/views/layouts/_social_metatags.html.haml
%meta{content: ENV['FB_APP_ID'], property: "fb:app_id"}
%meta{content: "gifgiraffe", name: "twitter:site"}
%meta{content: "giffare.com", name: "twitter:domain"}
%meta{content: gif.title, name: "twitter:title"}

%meta{content: gif_url(gif), property: "og:url"}
%meta{content: "Giffare", property: "og:site_name"}
%meta{content: gif.title, property: "og:title"}

%link{href: gif.url, rel: "image_src"}

- if gif.videoable?
  %meta{content: gif.url_for_format('.jpg'), property: "og:image"}
  %meta{content: "video.other", property: "og:type"}
  / %meta{content: "", property: "og:image:width"}
  / %meta{content: "", property: "og:image:height"}
  %meta{content: "http://s.imgur.com/include/flash/gifplayer.swf?imgur_video=#{gif.url_for_format('.mp4')}&imgur_width=660&imgur_height=370&imgur_url=#{gif.url_for_format('')}", property: "og:video"}
  %meta{content: "http://s.imgur.com/include/flash/gifplayer.swf?imgur_video=#{gif.url_for_format('.mp4')}&imgur_width=660&imgur_height=370&imgur_url=#{gif.url_for_format('')}".gsub('http://', 'https://'), property: "og:video:secure_url"}
  %meta{content: "application/x-shockwave-flash", property: "og:video:type"}
  %meta{content: gif.url_for_format('.mp4'), property: "og:video"}
  %meta{content: "video/mp4", property: "og:video:type"}
  / %meta{content: "", property: "og:video:width"}
  / %meta{content: "", property: "og:video:height"}

  %meta{content: "575", name: "twitter:player:width"}
  %meta{content: "409", name: "twitter:player:height"}
  %meta{content: gif.url_for_format(".gifv", "?twitter#t").gsub('http://', 'https://'), name: "twitter:player"}
  %meta{content: "player", name: "twitter:card"}
  %meta{content: gif.url_for_format(".mp4"), name: "twitter:player:stream"}
  %meta{content: "video/mp4", name: "twitter:player:stream:content_type"}
  %meta{content: gif.url_for_format('.jpg'), name: "twitter:image"}
  %meta{content: gif.url_for_format('.jpg'), name: "twitter:image:src"}
- else
  %meta{content: gif.url, property: "og:image"}
  %meta{content: gif.url, name: "twitter:image"}
  %meta{content: gif.url, name: "twitter:image:src"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= "Giffare - #{title}"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{charset: "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", content: "IE=edge,chrome=1"}
    %meta{name: "apple-mobile-web-app-capable", content: "yes" }
    %meta{name: "apple-mobile-web-app-status-bar-style", content: "black" }
    %meta{name: "viewport", content:  "width = device-width, height = device-height, user-scalable = yes" }
    = render 'layouts/social_metatags', gif: @gif if @gif
  %body
    = render 'social/facebook_integration'
    #main_header
      .content
        .search_form
          = form_tag gif_search_results_path, method: :get do
            = text_field_tag :q, params[:q], placeholder: "e.g. cats", class: 'search_field'
            = submit_tag 'Find', class: 'big_button'
        %h1
          = link_to "Giffare.com", root_url
    .content
      = yield
      #loading_indicator.user_message.for_later
        Loading more awesome gifs...
      #no_moar.user_message.for_later
        IMPRESSIVE: You have seen all the gifs now!
        = link_to "Giffare on twitter", 'http://twitter.com/gifgiraffe'

    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-4264346-6']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

app/views/sitemap/index.xml.haml
!!! XML
%urlset{:xmlns => "http://www.sitemaps.org/schemas/sitemap/0.9"}
  %url
    %loc= root_url
    %lastmod= @gifs.last.updated_at.strftime "%Y-%m-%d"
    %changefreq daily
    %priority 0.3
  - for i in (2..@gifs.size/Gif.default_per_page) do
    %url
      %loc= gifs_url(page: i)
      %lastmod= @gifs.last.updated_at.strftime "%Y-%m-%d"
      %changefreq daily
      %priority 0.3
  - for gif in @gifs
    %url
      %loc= gif_url gif
      %lastmod= gif.updated_at.strftime "%Y-%m-%d"
      %changefreq yearly

app/views/social/_facebook_integration.html.haml
#fb-root
:javascript
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '437368119609743', // App ID
      channelUrl : 'http://giffare.com/channel.html', // Channel File
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });
  };

  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));

app/views/social/_share.html.haml
= link_to image_tag('tweet.png', width: "66px", height: "24px"), "https://twitter.com/share?text=#{gif.title.to_s.gsub(/ /, '+')}&url=#{CGI.escape gif_url(gif)}", class: 'tweet_button', target: :blank

.fb-like{"data-font" => "arial", "data-href" => gif_url(gif), "data-layout" => "button_count", "data-send" => "false", "data-show-faces" => "false", "data-width" => "70"}

%a{href: "https://plus.google.com/share?url=#{gif_url(gif)}", onclick: "javascript:window.open(this.href,\r\n  '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"}
  = image_tag "gplus.png", title: "Share on Google+", width: "66px", height: "24px"

app/views/unpublished_gifs/_form.html.haml
.page
  - action = :create
  - if gif.persisted?
    - action = :update
    %h3= gif.title
    %br
    = image_tag gif.directified_url, class: 'preview'
    %p= link_to gif.url, gif.url
  %br
  = form_for gif, remote: remote, url: { controller: :unpublished_gifs, action: action, id: gif.id } do |f|
    = f.text_field :title, placeholder: 'title'
    %br
    = f.text_field :url, placeholder: 'url', value: gif.directified_url
    %br
    = f.datetime_select :published_at
    = f.label :published_at
    %br
    = label_tag do
      = f.check_box :nsfw
      Adult, porn, NSFW...
    %br
    = label_tag nil, class: 'destructive_action' do
      = f.check_box :hidden
      Send to trash
    %br
    %br
    = label_tag do
      = f.check_box :social_share
      Share on social networks
    %br
    %br
    = f.submit "Save", class: 'js_gif_submit'

app/views/unpublished_gifs/edit.html.haml
= render 'form', gif: gif, remote: false
= link_to "Delete", unpublished_gif_path(gif), method: :delete, data: { confirm: 'Are you sure?' }

app/views/unpublished_gifs/index.html.haml
#bulk_edit
  = paginate gifs
  - gifs.each do |gif|
    .editable_gif
      .hidden.done
        Saved
        = link_to "View", gif_path(gif), target: "_blank"
        = render "social/share", gif: gif
      = render "form", gif: gif, remote: true
      -# = button_to 'Delete', gif, method: :delete, remote: true, confirm: 'U sure?'
  = paginate gifs
  .editable_gif
    = link_to "Import more", import_gifs_path(admin: true)
    |
    = link_to "Empty trash", empty_trash_unpublished_gifs_path, method: :delete, data: { confirm: "Are you sure?" }
    |
    = link_to "Delete all unpublished", delete_all_unpublished_gifs_path, method: :delete, data: { confirm: "Are you sure?" }

app/views/unpublished_gifs/new.html.haml
= render 'form', gif: Gif.new, remote: false